"""BarrelLabs Swing Report — v2 PDF renderer.

Mirrors the on-screen v2 layout in a dark-theme
ReportLab PDF: hero with score ring + coach blurb, MLB comp card, 4 key
metric tiles with mini sparklines, 5-axis radar, detailed mechanic
breakdown, top priorities, drill plan, score-history line chart, next
step CTA, and full coach notes.

Imported and dispatched from `swing_report.build_swing_report_pdf`,
which now delegates here unconditionally (the legacy light-theme v1
PDF body has been retired).
"""

from __future__ import annotations

import math
import re
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Pull data helpers from the v1 module (already battle-tested in prod)
from swing_report import (
    coach_summary,
    top_three_fixes,
    swing_dna,
    mlb_signature_traits,
    swing_progress,
    enrich_fixes_with_history,
    _extract_ref_info,
    _initials,
)

# Shared metric helpers provide the key-metric tile definitions + flatteners
from swing_metrics import (
    _V2_TILES,
    _flatten_metric_table,
    _find_metric_row,
    _parse_value_from_str,
)


# ============================================================
#                       ENTRY POINT
# ============================================================


def build_swing_report_pdf_v2(
    record: Dict[str, Any],
    history: Optional[List[Dict[str, Any]]] = None,
) -> bytes:
    """Produce the v2 dark-theme swing report PDF and return raw bytes."""
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    from reportlab.lib.utils import ImageReader
    from reportlab.pdfbase.pdfmetrics import stringWidth

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    W, H = letter

    # ====================================================================
    #                        DESIGN TOKENS
    # ====================================================================
    MARGIN = 42
    # Vertical rhythm after a section eyebrow — single constant so every
    # section starts at the same distance from its header.
    SECTION_GAP = 20

    # Dark palette — mirrors the bld2-* CSS variables from the v2 web layout
    BG          = colors.HexColor("#0a0a0c")
    SURFACE_0   = colors.HexColor("#0f0f12")
    SURFACE_1   = colors.HexColor("#15151a")
    SURFACE_2   = colors.HexColor("#1c1c22")
    LINE        = colors.HexColor("#1f1f25")
    LINE_2      = colors.HexColor("#2a2a32")
    INK_100     = colors.HexColor("#f5f5f7")
    INK_80      = colors.HexColor("#cdcdd2")
    INK_60      = colors.HexColor("#8a8a92")
    INK_40      = colors.HexColor("#5a5a62")
    RED         = colors.HexColor("#ff3b30")
    RED_DIM     = colors.HexColor("#3a151a")
    GREEN       = colors.HexColor("#6ee7b7")
    GREEN_DIM   = colors.HexColor("#143028")
    AMBER       = colors.HexColor("#fbbf24")
    AMBER_DIM   = colors.HexColor("#3a2a10")

    # ====================================================================
    #                        STATE / HELPERS
    # ====================================================================
    state = {"page": 1}
    y = H - 50  # top cursor — set after header on page 1

    def fill_page_bg():
        """Paint the whole page dark before any content lands on it."""
        c.setFillColor(BG)
        c.rect(0, 0, W, H, fill=1, stroke=0)

    def footer(page_num: int):
        c.setStrokeColor(LINE)
        c.setLineWidth(0.5)
        c.line(MARGIN, 32, W - MARGIN, 32)
        c.setFillColor(INK_60)
        c.setFont("Helvetica", 7.5)
        c.drawString(MARGIN, 20, "BARRELLABS  ·  Built for Better Swings")
        c.drawCentredString(W / 2, 20, f"Page {page_num}")
        c.drawRightString(W - MARGIN, 20, "Generated by SwingAI")

    def new_page():
        nonlocal y
        footer(state["page"])
        c.showPage()
        state["page"] += 1
        fill_page_bg()
        y = H - 50

    def need_space(amount: float):
        nonlocal y
        # Bottom guard: footer line is at y=32, footer text at y=20.
        # 42 leaves ~10pt clearance between content bottom and footer line.
        if y - amount < 42:
            new_page()

    def fit_text(text: str, font: str, size: float, max_w: float) -> str:
        if stringWidth(text, font, size) <= max_w:
            return text
        ell = "…"
        ell_w = stringWidth(ell, font, size)
        for i in range(len(text) - 1, 0, -1):
            cand = text[:i]
            if stringWidth(cand, font, size) + ell_w <= max_w:
                return cand + ell
        return ell

    def wrapped_lines(text: str, font: str, size: float, max_w: float) -> List[str]:
        words = str(text).replace("\n", " ").split()
        lines: List[str] = []
        cur = ""
        for word in words:
            test = (cur + " " + word).strip()
            if stringWidth(test, font, size) <= max_w:
                cur = test
            else:
                if cur:
                    lines.append(cur)
                cur = word
        if cur:
            lines.append(cur)
        return lines

    def draw_wrapped(text: str, x: float, y_pos: float, max_w: float,
                     *, font="Helvetica", size=9.5, leading=13,
                     color=INK_80, max_lines: Optional[int] = None) -> float:
        c.setFont(font, size)
        c.setFillColor(color)
        lines = wrapped_lines(text, font, size, max_w)
        if max_lines is not None and len(lines) > max_lines:
            lines = lines[:max_lines]
            lines[-1] = fit_text(lines[-1] + " …", font, size, max_w)
        cur_y = y_pos
        for line in lines:
            c.drawString(x, cur_y, line)
            cur_y -= leading
        return cur_y

    def card(x: float, y_top: float, w: float, h: float,
             *, fill=SURFACE_0, stroke=LINE, radius=10):
        c.setFillColor(fill)
        c.setStrokeColor(stroke)
        c.setLineWidth(0.6)
        c.roundRect(x, y_top - h, w, h, radius, fill=1, stroke=1)
        c.setLineWidth(1)

    def eyebrow(x: float, y_pos: float, text: str, color=INK_60):
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 7)
        # Letter-space the text manually since reportlab doesn't expose tracking
        c.drawString(x, y_pos, text.upper())

    def red_dot(x: float, y_pos: float, r: float = 2.5):
        c.setFillColor(RED)
        c.circle(x, y_pos, r, fill=1, stroke=0)

    def pill(x: float, y_pos: float, text: str,
             *, fg=RED, bg=RED_DIM, border=None,
             size: float = 7.5, padding_x: float = 8, h: float = 14):
        if border is None:
            border = fg
        tw = stringWidth(text, "Helvetica-Bold", size) + padding_x * 2
        c.setFillColor(bg)
        c.setStrokeColor(border)
        c.setLineWidth(0.6)
        c.roundRect(x, y_pos, tw, h, h / 2, fill=1, stroke=1)
        c.setFillColor(fg)
        c.setFont("Helvetica-Bold", size)
        c.drawString(x + padding_x, y_pos + h / 2 - size / 2 + 0.5, text)
        c.setLineWidth(1)
        return tw

    def section_eyebrow(num: str, label: str):
        """Two-digit number + spaced label, dot-prefixed — mirrors v2.

        Adds a glowing red dot before the section number to visually match
        the web report's .bld2-eyebrow::before accent. The number itself is
        rendered in RED to draw the eye to the section index; the label
        stays in INK_60 muted gray for hierarchy.
        """
        nonlocal y
        # Red accent dot
        c.setFillColor(RED)
        c.circle(MARGIN + 4, y + 2.5, 2, fill=1, stroke=0)
        # Section number in red, label in muted gray
        c.setFont("Helvetica-Bold", 7.5)
        c.setFillColor(RED)
        num_text = f"{num}"
        c.drawString(MARGIN + 12, y, num_text)
        num_w = stringWidth(num_text, "Helvetica-Bold", 7.5)
        c.setFillColor(INK_60)
        c.drawString(MARGIN + 12 + num_w + 8, y, label.upper())
        y -= SECTION_GAP

    def band_for_score(score) -> Tuple[str, colors.Color, colors.Color]:
        try:
            s = float(score)
        except Exception:
            return "—", INK_40, SURFACE_2
        if s >= 80: return "ELITE MECHANICS",   GREEN, GREEN_DIM
        if s >= 60: return "STRONG FOUNDATION", AMBER, AMBER_DIM
        if s >= 40: return "BUILDING BLOCK",    RED,   RED_DIM
        return "GROUND FLOOR", RED, RED_DIM

    def band_color_for_pct(pct) -> colors.Color:
        try:
            p = float(pct)
        except Exception:
            return RED
        if p >= 80: return GREEN
        if p >= 60: return AMBER
        return RED

    def strip_html(text: str) -> str:
        return re.sub(r"<[^>]+>", "", text or "")

    # ====================================================================
    #                        SCORE RING (donut)
    # ====================================================================
    def score_ring(cx: float, cy: float, r: float, score: int,
                   band_color: colors.Color, thickness: float = 8):
        c.setStrokeColor(SURFACE_2)
        c.setLineWidth(thickness)
        c.circle(cx, cy, r, stroke=1, fill=0)

        pct = max(0.0, min(1.0, score / 100.0))
        if pct > 0:
            c.setStrokeColor(band_color)
            c.setLineCap(1)
            sweep = -360.0 * pct
            c.arc(cx - r, cy - r, cx + r, cy + r, 90, sweep)
            c.setLineCap(0)

        c.setLineWidth(1)
        c.setFillColor(band_color)
        c.setFont("Helvetica-Bold", 22)
        s = str(score)
        sw = stringWidth(s, "Helvetica-Bold", 22)
        c.drawString(cx - sw / 2, cy - 6, s)
        c.setFillColor(INK_60)
        c.setFont("Helvetica", 7)
        c.drawCentredString(cx, cy - 18, "/ 100")

    # ====================================================================
    #                        SPARKLINE
    # ====================================================================
    def sparkline(values: List[float], x: float, y_pos: float,
                  w: float, h: float, color: colors.Color = RED):
        """Mini line chart inside a tile — same vibe as the v2 SVG sparkline."""
        if len(values) < 2:
            c.setStrokeColor(INK_40)
            c.setLineWidth(1)
            c.line(x, y_pos + h / 2, x + w, y_pos + h / 2)
            c.setLineWidth(1)
            return

        v_min, v_max = min(values), max(values)
        v_span = max(v_max - v_min, 1e-6)
        n = len(values)

        def _x(i): return x + (i / (n - 1)) * w
        def _y(v): return y_pos + ((v - v_min) / v_span) * h

        # Soft gradient-feeling fill (single tone since reportlab gradient
        # is annoying — we fake it with a low-alpha-equivalent dark fill)
        path = c.beginPath()
        path.moveTo(_x(0), y_pos)
        for i, v in enumerate(values):
            path.lineTo(_x(i), _y(v))
        path.lineTo(_x(n - 1), y_pos)
        path.close()
        c.setFillColor(SURFACE_2)
        c.drawPath(path, fill=1, stroke=0)

        # Stroke the top line
        c.setStrokeColor(color)
        c.setLineWidth(1.4)
        c.setLineCap(1)
        c.setLineJoin(1)
        line_path = c.beginPath()
        line_path.moveTo(_x(0), _y(values[0]))
        for i in range(1, n):
            line_path.lineTo(_x(i), _y(values[i]))
        c.drawPath(line_path, fill=0, stroke=1)

        # Endpoint dot
        c.setFillColor(color)
        c.circle(_x(n - 1), _y(values[-1]), 1.6, fill=1, stroke=0)

        c.setLineWidth(1)
        c.setLineCap(0)
        c.setLineJoin(0)

    # ====================================================================
    #                        RADAR CHART
    # ====================================================================
    def radar_chart(axes: List[Tuple[str, float]], cx: float, cy: float,
                    radius: float):
        n = max(len(axes), 3)
        levels = [0.25, 0.5, 0.75, 1.0]
        # ReportLab PDF coordinate space has y INCREASING upward (math
        # convention), opposite of SVG/HTML where y goes down. So to put
        # axis-0 at the visual top of the radar, start at +π/2 and rotate
        # clockwise as you walk the list of axes.
        angles = [math.pi / 2 - i * (2 * math.pi / n) for i in range(n)]

        # Grid pentagons
        c.setStrokeColor(LINE_2)
        c.setLineWidth(0.5)
        for lvl in levels:
            pts = []
            for a in angles:
                pts.append((cx + math.cos(a) * radius * lvl,
                            cy + math.sin(a) * radius * lvl))
            p = c.beginPath()
            p.moveTo(*pts[0])
            for px, py in pts[1:]:
                p.lineTo(px, py)
            p.close()
            c.drawPath(p, fill=0, stroke=1)

        # Axis lines + labels
        c.setStrokeColor(LINE_2)
        c.setLineWidth(0.5)
        for a, (label, _pct) in zip(angles, axes):
            ex = cx + math.cos(a) * radius
            ey = cy + math.sin(a) * radius
            c.line(cx, cy, ex, ey)
            lx = cx + math.cos(a) * (radius + 14)
            ly = cy + math.sin(a) * (radius + 14)
            c.setFillColor(INK_60)
            c.setFont("Helvetica-Bold", 6.5)
            if math.cos(a) > 0.3:
                c.drawString(lx, ly - 2, label.upper())
            elif math.cos(a) < -0.3:
                tw = stringWidth(label.upper(), "Helvetica-Bold", 6.5)
                c.drawString(lx - tw, ly - 2, label.upper())
            else:
                c.drawCentredString(lx, ly - 2, label.upper())

        # MLB reference polygon (100% on every axis = dashed pentagon)
        ref_pts = []
        for a in angles:
            ref_pts.append((cx + math.cos(a) * radius,
                            cy + math.sin(a) * radius))
        c.setStrokeColor(GREEN)
        c.setLineWidth(0.8)
        c.setDash(3, 3)
        p = c.beginPath()
        p.moveTo(*ref_pts[0])
        for px, py in ref_pts[1:]:
            p.lineTo(px, py)
        p.close()
        c.drawPath(p, fill=0, stroke=1)
        c.setDash()

        # Player polygon
        player_pts = []
        for a, (_label, pct) in zip(angles, axes):
            pct = max(0.0, min(100.0, float(pct or 0.0)))
            rr = radius * (pct / 100.0)
            player_pts.append((cx + math.cos(a) * rr,
                               cy + math.sin(a) * rr))
        c.setFillColor(RED_DIM)
        c.setStrokeColor(RED)
        c.setLineWidth(1.4)
        p = c.beginPath()
        p.moveTo(*player_pts[0])
        for px, py in player_pts[1:]:
            p.lineTo(px, py)
        p.close()
        c.drawPath(p, fill=1, stroke=1)

        # Player dots
        c.setFillColor(RED)
        for px, py in player_pts:
            c.circle(px, py, 2.2, fill=1, stroke=0)

        c.setLineWidth(1)

    # ====================================================================
    #                        PAGE 1 — TOP HEADER BAND
    # ====================================================================
    fill_page_bg()

    # Logo + title in dark band — full-bleed top
    c.setFillColor(SURFACE_1)
    c.rect(0, H - 110, W, 110, fill=1, stroke=0)
    c.setStrokeColor(RED)
    c.setLineWidth(2)
    c.line(0, H - 110, W, H - 110)
    c.setLineWidth(1)

    logo_offset = 0
    logo_path = Path("barrellabs_logo.png")
    if logo_path.exists():
        try:
            c.drawImage(
                ImageReader(str(logo_path)),
                MARGIN, H - 90, width=52, height=52, mask="auto",
            )
            logo_offset = 66
        except Exception:
            logo_offset = 0

    c.setFillColor(RED)
    c.setFont("Helvetica-Bold", 7.5)
    c.drawString(MARGIN + logo_offset, H - 48,
                 "BARRELLABS PERFORMANCE LAB")

    c.setFillColor(INK_100)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(MARGIN + logo_offset, H - 74, "Swing Report")

    c.setFillColor(INK_60)
    c.setFont("Helvetica", 8.5)
    c.drawString(MARGIN + logo_offset, H - 90,
                 "AI swing analysis  ·  MLB comparison  ·  personalized development plan")

    y = H - 134

    # ====================================================================
    #                        EYEBROW + META + PILL
    # ====================================================================
    is_live = not record.get("id")
    swing_num = record.get("swing_number")
    date_str = record.get("date", "Saved swing")
    if swing_num:
        eyebrow_text = f"SAVED REPORT  ·  SWING #{swing_num}"
    elif is_live:
        eyebrow_text = "LIVE ANALYSIS"
    else:
        eyebrow_text = "SAVED REPORT"

    c.setFillColor(RED)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(MARGIN, y, eyebrow_text)

    c.setFillColor(INK_60)
    c.setFont("Helvetica", 8.5)
    c.drawString(MARGIN, y - 14, date_str)

    file_name = record.get("file_name") or record.get("video_name")
    if file_name:
        f_short = fit_text(str(file_name), "Helvetica", 8.5, 200)
        c.drawString(MARGIN + 130, y - 14, f"FILE  {f_short}")

    pill_label = "NEW ANALYSIS" if is_live else "SAVED REPORT"
    pill_fg = RED if is_live else AMBER
    pill_bg = RED_DIM if is_live else AMBER_DIM
    tw = stringWidth(pill_label, "Helvetica-Bold", 7.5) + 16
    pill(W - MARGIN - tw, y - 4, pill_label,
         fg=pill_fg, bg=pill_bg, border=pill_fg, size=7.5)

    y -= 36

    # ====================================================================
    #                        HERO STRIP (split)
    # ====================================================================
    score_raw = record.get("score") or 0
    try:
        score_int = int(round(float(score_raw)))
    except Exception:
        score_int = 0
    band_label, band_color, band_bg = band_for_score(score_int)

    hero_h = 200
    need_space(hero_h + 10)

    # Left card: score + coach blurb (~62% width)
    left_w = (W - MARGIN * 2) * 0.62 - 5
    right_w = (W - MARGIN * 2) * 0.38 - 5

    card(MARGIN, y, left_w, hero_h, fill=SURFACE_0, stroke=LINE)

    # Eyebrow with red dot
    red_dot(MARGIN + 16, y - 18, 2.5)
    eyebrow(MARGIN + 24, y - 21, "OVERALL SWING SCORE")

    # Big red score number
    c.setFillColor(RED)
    c.setFont("Helvetica-Bold", 56)
    c.drawString(MARGIN + 16, y - 78, str(score_int))
    foot_w = stringWidth(str(score_int), "Helvetica-Bold", 56)
    c.setFillColor(INK_60)
    c.setFont("Helvetica", 11)
    c.drawString(MARGIN + 16 + foot_w + 6, y - 70, "/ 100")

    # Band pill under score
    pill(MARGIN + 16, y - 98, band_label,
         fg=band_color, bg=band_bg, border=band_color,
         size=7, padding_x=9, h=13)

    # Delta vs previous
    prog = swing_progress(record, history)
    delta_y = y - 122
    if prog and prog.get("has_prior"):
        delta = prog.get("score_delta")
        prev_int = int(round(float(prog.get("prev_score") or 0)))
        if delta is None:
            d_text = "—"; d_color = INK_60
        elif delta > 0:
            d_text = f"↑ +{abs(delta):.0f} VS PREVIOUS ({prev_int})"; d_color = GREEN
        elif delta < 0:
            d_text = f"↓ {abs(delta):.0f} VS PREVIOUS ({prev_int})"; d_color = RED
        else:
            d_text = f"± 0 VS PREVIOUS ({prev_int})"; d_color = INK_60
        c.setFillColor(d_color)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(MARGIN + 16, delta_y, d_text)

    # Coach blurb (HTML-stripped — no <strong> tags in PDF)
    blurb_text = strip_html(coach_summary(record))
    blurb_y = y - 145
    draw_wrapped(blurb_text, MARGIN + 16, blurb_y,
                 left_w - 32, font="Helvetica", size=9.5,
                 leading=13, color=INK_80, max_lines=4)

    # Right card: MLB comp + score ring
    right_x = MARGIN + left_w + 10
    card(right_x, y, right_w, hero_h, fill=SURFACE_0, stroke=LINE)

    red_dot(right_x + 16, y - 18, 2.5)
    eyebrow(right_x + 24, y - 21, "MLB COMPARISON")

    ref = _extract_ref_info(record)
    ref_name = str(ref.get("name", "—"))
    ref_initials = _initials(ref_name) or "—"

    # Avatar circle
    av_cx = right_x + 38
    av_cy = y - 70
    c.setFillColor(SURFACE_2)
    c.setStrokeColor(LINE_2)
    c.circle(av_cx, av_cy, 22, fill=1, stroke=1)
    c.setFillColor(RED)
    c.setFont("Helvetica-Bold", 14)
    iw = stringWidth(ref_initials, "Helvetica-Bold", 14)
    c.drawString(av_cx - iw / 2, av_cy - 5, ref_initials)

    # Name + meta to the right of avatar
    name_x = av_cx + 32
    name_w = right_w - (name_x - right_x) - 16
    c.setFillColor(INK_100)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(name_x, av_cy + 6,
                 fit_text(ref_name, "Helvetica-Bold", 13, name_w))

    meta_parts = []
    if ref.get("team"):     meta_parts.append(str(ref["team"]))
    if ref.get("position"): meta_parts.append(str(ref["position"]))
    if meta_parts:
        c.setFillColor(INK_60)
        c.setFont("Helvetica", 8)
        c.drawString(name_x, av_cy - 8,
                     fit_text("  ·  ".join(meta_parts), "Helvetica",
                              8, name_w))

    # Style line under avatar
    if ref.get("style"):
        c.setFillColor(INK_80)
        c.setFont("Helvetica-Oblique", 8.5)
        draw_wrapped(str(ref["style"]), right_x + 16, y - 108,
                     right_w - 32, font="Helvetica-Oblique",
                     size=8.5, leading=11, color=INK_80, max_lines=2)

    # Trait chips at the bottom
    traits = mlb_signature_traits(ref_name) or []
    if traits:
        chip_x = right_x + 16
        chip_y = y - 170
        for t in traits[:3]:
            label = t.upper()
            tw = stringWidth(label, "Helvetica-Bold", 6.5) + 12
            if chip_x + tw > right_x + right_w - 16:
                break
            c.setFillColor(SURFACE_2)
            c.setStrokeColor(LINE_2)
            c.setLineWidth(0.5)
            c.roundRect(chip_x, chip_y, tw, 12, 6, fill=1, stroke=1)
            c.setFillColor(INK_80)
            c.setFont("Helvetica-Bold", 6.5)
            c.drawString(chip_x + 6, chip_y + 3.5, label)
            chip_x += tw + 4
        c.setLineWidth(1)

    y -= hero_h + 14

    # ====================================================================
    #                       TOP PRIORITIES
    # (Rendered immediately after the hero — actionable insights belong at
    #  the top so the reader sees WHAT TO FIX before scrolling through the
    #  diagnostic charts. Mirrors the web report's section order.)
    # ====================================================================
    fixes = top_three_fixes(record)
    if history:
        try:
            fixes = enrich_fixes_with_history(fixes, record, history)
        except Exception:
            pass

    if fixes:
        need_space(160)
        section_eyebrow("03", "Top Priorities")

        for fx in fixes:
            body_w = W - MARGIN * 2 - 80
            line_h = 12

            coach_memory = ""
            if fx.get("is_recurring"):
                first_n = fx.get("first_flagged_in")
                prev_p = fx.get("prev_sim_pct")
                curr_p = fx.get("curr_sim_pct")
                delta_pp = fx.get("delta_since_last")
                parts = []
                if first_n is not None:
                    parts.append(f"Same flag in Swing #{first_n}.")
                else:
                    parts.append("Flagged before.")
                if (delta_pp is not None and prev_p is not None
                        and curr_p is not None):
                    if delta_pp > 1.0:
                        parts.append(
                            f"You've closed +{delta_pp:.1f}% on this category "
                            f"({int(round(prev_p))}% → {int(round(curr_p))}%) — keep stacking it."
                        )
                    elif delta_pp < -1.0:
                        parts.append(
                            f"Slipped {delta_pp:.1f}% "
                            f"({int(round(prev_p))}% → {int(round(curr_p))}%) — revisit this drill block."
                        )
                    else:
                        parts.append(
                            f"Match % held flat at {int(round(curr_p))}% — small unlock, big payoff."
                        )
                else:
                    parts.append("If it keeps showing up, prioritize the drill below.")
                coach_memory = " ".join(parts)

            body_lines: List[Tuple[str, str]] = []
            if fx.get("headline"):
                for ln in wrapped_lines(fx["headline"], "Helvetica", 9.5, body_w):
                    body_lines.append(("body", ln))
            if fx.get("why"):
                body_lines.append(("label", "WHY IT COSTS YOU"))
                for ln in wrapped_lines(fx["why"], "Helvetica", 9.5, body_w):
                    body_lines.append(("body", ln))
            if fx.get("fix_feel"):
                body_lines.append(("label", "WHAT THE FIX FEELS LIKE"))
                for ln in wrapped_lines(fx["fix_feel"], "Helvetica", 9.5, body_w):
                    body_lines.append(("body", ln))
            if coach_memory:
                body_lines.append(("label", "COACH MEMORY"))
                for ln in wrapped_lines(coach_memory, "Helvetica", 9.5, body_w):
                    body_lines.append(("body", ln))

            body_h = 0
            for kind, _ in body_lines:
                body_h += (line_h + 1 if kind == "label" else line_h)
            card_h = 38 + body_h + 14
            need_space(card_h + 8)

            card(MARGIN, y, W - MARGIN * 2, card_h,
                 fill=SURFACE_0, stroke=LINE)

            # Rank chip
            chip_x = MARGIN + 14
            chip_y = y - 32
            c.setFillColor(RED)
            c.roundRect(chip_x, chip_y, 28, 28, 6, fill=1, stroke=0)
            c.setFillColor(colors.white)
            c.setFont("Helvetica-Bold", 14)
            c.drawCentredString(chip_x + 14, chip_y + 9, str(fx.get("rank", "·")))

            # Title
            c.setFillColor(INK_100)
            c.setFont("Helvetica-Bold", 11.5)
            c.drawString(chip_x + 38, chip_y + 17,
                         fit_text(str(fx.get("title", "")),
                                  "Helvetica-Bold", 11.5, body_w - 80))

            # Severity pill
            sev_map = {
                "high": ("HIGH IMPACT", RED, RED_DIM),
                "med":  ("MED IMPACT",  AMBER, AMBER_DIM),
                "low":  ("LOW IMPACT",  GREEN, GREEN_DIM),
            }
            sev_label, sev_color, sev_bg = sev_map.get(
                fx.get("severity"), ("IMPACT", INK_60, SURFACE_2))
            tw = stringWidth(sev_label, "Helvetica-Bold", 7) + 14
            pill(W - MARGIN - 14 - tw, chip_y + 9, sev_label,
                 fg=sev_color, bg=sev_bg, border=sev_color, size=7,
                 padding_x=7, h=13)

            # Body
            cur_y = y - 58
            for kind, line in body_lines:
                if kind == "label":
                    c.setFillColor(RED)
                    c.setFont("Helvetica-Bold", 6.5)
                    c.drawString(chip_x + 38, cur_y, line)
                    cur_y -= line_h + 1
                else:
                    c.setFillColor(INK_80)
                    c.setFont("Helvetica", 9.5)
                    c.drawString(chip_x + 38, cur_y, line)
                    cur_y -= line_h

            y -= card_h + 10

    # ====================================================================
    #                       DRILL PLAN
    # ====================================================================
    drill_plan = record.get("drill_plan") or {}
    cats = drill_plan.get("categories", []) if isinstance(drill_plan, dict) else []
    if cats:
        need_space(60)
        section_eyebrow("04", "Personalized Drill Plan")

        for cat in cats:
            drills = cat.get("drills", []) or []
            priority = cat.get("priority", "·")
            title = str(cat.get("title", "Drills"))
            why = cat.get("why_it_matters", "")

            why_lines = wrapped_lines(why, "Helvetica-Oblique", 9,
                                      W - MARGIN * 2 - 28) if why else []
            drill_rows_h = 0
            for d in drills:
                how_lines = wrapped_lines(d.get("how", ""), "Helvetica", 9,
                                          W - MARGIN * 2 - 64)[:3]
                drill_rows_h += 16 + (len(how_lines) * 11) + 6
            cat_h = 38 + (len(why_lines) * 12) + drill_rows_h + 8
            need_space(cat_h + 10)

            card(MARGIN, y, W - MARGIN * 2, cat_h,
                 fill=SURFACE_0, stroke=LINE)

            # Priority header strip
            c.setFillColor(SURFACE_1)
            c.rect(MARGIN, y - 28, W - MARGIN * 2, 28, fill=1, stroke=0)
            # Re-stroke top border since rect wiped the round corner top
            c.setStrokeColor(LINE)
            c.setLineWidth(0.6)
            c.line(MARGIN, y, W - MARGIN, y)
            c.setLineWidth(1)

            c.setFillColor(RED)
            c.roundRect(MARGIN + 14, y - 22, 22, 16, 4, fill=1, stroke=0)
            c.setFillColor(colors.white)
            c.setFont("Helvetica-Bold", 9)
            c.drawCentredString(MARGIN + 25, y - 17, str(priority))

            c.setFillColor(INK_100)
            c.setFont("Helvetica-Bold", 11)
            c.drawString(MARGIN + 44, y - 18,
                         fit_text(title, "Helvetica-Bold", 11,
                                  W - MARGIN * 2 - 140))

            cnt_str = f"{len(drills)} DRILL{'S' if len(drills) != 1 else ''}"
            c.setFillColor(INK_60)
            c.setFont("Helvetica-Bold", 7.5)
            c.drawRightString(W - MARGIN - 14, y - 18, cnt_str)

            cur_y = y - 42
            if why_lines:
                c.setFillColor(INK_60)
                c.setFont("Helvetica-Oblique", 9)
                for line in why_lines:
                    c.drawString(MARGIN + 16, cur_y, line)
                    cur_y -= 12
                cur_y -= 2

            for j, d in enumerate(drills, 1):
                name = str(d.get("name", "Drill"))
                reps = str(d.get("reps", "")).strip()
                how = str(d.get("how", "")).strip()

                # Red left bar
                c.setFillColor(RED)
                c.rect(MARGIN + 16, cur_y - 12, 2, 12, fill=1, stroke=0)
                # Name
                c.setFillColor(INK_100)
                c.setFont("Helvetica-Bold", 9.5)
                c.drawString(MARGIN + 24, cur_y - 4,
                             fit_text(f"{j}. {name}", "Helvetica-Bold", 9.5,
                                      W - MARGIN * 2 - 110))
                if reps:
                    rw = stringWidth(reps, "Helvetica", 8) + 14
                    c.setFillColor(SURFACE_2)
                    c.setStrokeColor(LINE_2)
                    c.setLineWidth(0.5)
                    c.roundRect(W - MARGIN - 14 - rw, cur_y - 8, rw, 13, 6,
                                fill=1, stroke=1)
                    c.setFillColor(INK_80)
                    c.setFont("Helvetica", 8)
                    c.drawString(W - MARGIN - 14 - rw + 7, cur_y - 5, reps)
                    c.setLineWidth(1)

                cur_y -= 14

                if how:
                    how_lines = wrapped_lines(how, "Helvetica", 9,
                                              W - MARGIN * 2 - 44)[:3]
                    c.setFillColor(INK_60)
                    c.setFont("Helvetica", 9)
                    for line in how_lines:
                        c.drawString(MARGIN + 24, cur_y, line)
                        cur_y -= 11
                cur_y -= 4

            y -= cat_h + 12

    # ====================================================================
    #                        KEY METRICS STRIP (4 tiles + sparklines)
    # ====================================================================
    need_space(120)
    section_eyebrow("05", "Key Metrics")

    # Pull the 4 most-relevant tiles for the strip (mirrors v2 — first 4
    # of _V2_TILES which cover rotation, separation, timing, contact).
    tile_defs = _V2_TILES[:4]
    curr_rows = _flatten_metric_table(record)

    # Build prev_rows + per-tile series for sparklines
    prev_rows: List[Dict[str, Any]] = []
    series_records: List[Dict[str, Any]] = []
    if history:
        sorted_hist = sorted(history,
                             key=lambda r: str(r.get("timestamp") or r.get("date") or ""))
        curr_id = record.get("id")
        curr_ts = record.get("timestamp")
        prior = [r for r in sorted_hist
                 if not ((curr_id is not None and r.get("id") == curr_id)
                         or (curr_ts is not None and r.get("timestamp") == curr_ts))]
        if prior:
            prev_rows = _flatten_metric_table(prior[-1])
        series_records = (prior[-7:] if prior else []) + [record]
    else:
        series_records = [record]

    tile_gap = 8
    tile_w = (W - MARGIN * 2 - tile_gap * 3) / 4
    tile_h = 96

    for i, (label, needle, unit_hint, direction) in enumerate(tile_defs):
        tx = MARGIN + i * (tile_w + tile_gap)
        card(tx, y, tile_w, tile_h, fill=SURFACE_0, stroke=LINE, radius=10)

        # Eyebrow
        c.setFillColor(INK_60)
        c.setFont("Helvetica-Bold", 6.5)
        c.drawString(tx + 12, y - 16, label)

        row = _find_metric_row(curr_rows, needle)
        if row is None:
            c.setFillColor(INK_40)
            c.setFont("Helvetica-Bold", 16)
            c.drawString(tx + 12, y - 40, "—")
            c.setFillColor(INK_60)
            c.setFont("Helvetica", 7.5)
            c.drawString(tx + 12, y - 56, "metric unavailable")
            continue

        val_str = str(row.get("player_str", "—")).lstrip("~+").strip()
        c.setFillColor(INK_100)
        c.setFont("Helvetica-Bold", 17)
        c.drawString(tx + 12, y - 40,
                     fit_text(val_str, "Helvetica-Bold", 17, tile_w - 24))

        # Delta vs previous
        if prev_rows:
            prev_row = _find_metric_row(prev_rows, needle)
            if prev_row is not None:
                cv = _parse_value_from_str(row.get("player_str", ""))
                pv = _parse_value_from_str(prev_row.get("player_str", ""))
                if cv is not None and pv is not None:
                    raw = cv - pv
                    if abs(raw) < 0.05:
                        d_text = "± 0"; d_color = INK_60
                    else:
                        sign = "↑" if raw > 0 else "↓"
                        if direction == "higher":
                            good = raw > 0
                        elif direction == "lower":
                            good = raw < 0
                        else:
                            cs = row.get("sim_pct", 0) or 0
                            ps = prev_row.get("sim_pct", 0) or 0
                            good = cs >= ps
                        d_color = GREEN if good else RED
                        d_text = f"{sign} {abs(raw):.1f}"
                    c.setFillColor(d_color)
                    c.setFont("Helvetica-Bold", 8)
                    c.drawString(tx + 12, y - 56, d_text)

        # Reference subtitle
        ref_short = str(row.get("ref_str", "")).lstrip("~+").strip()
        if ref_short:
            c.setFillColor(INK_60)
            c.setFont("Helvetica", 7)
            c.drawString(tx + tile_w - 12
                         - stringWidth(f"vs {ref_short}", "Helvetica", 7),
                         y - 56, f"vs {ref_short}")

        # Sparkline at bottom
        series_vals: List[float] = []
        for rec in series_records:
            rec_rows = _flatten_metric_table(rec)
            rec_row = _find_metric_row(rec_rows, needle)
            if rec_row is None:
                continue
            v = _parse_value_from_str(rec_row.get("player_str", ""))
            if v is not None:
                series_vals.append(v)
        sparkline(series_vals, tx + 12, y - 84, tile_w - 24, 20, RED)

    y -= tile_h + 22

    # ====================================================================
    #                        PAGE 2 — RADAR + BREAKDOWN
    # ====================================================================
    new_page()
    section_eyebrow("06", "Mechanical Fingerprint")

    # Compute radar axes — mirror v2 web's _sim_avg logic
    def _sim_avg(needles: List[str]) -> float:
        vals = []
        for nd in needles:
            r = _find_metric_row(curr_rows, nd)
            if r is not None and r.get("sim_pct") is not None:
                vals.append(float(r["sim_pct"]))
        return (sum(vals) / len(vals)) if vals else 0.0

    radar_axes = [
        ("ROTATION",   _sim_avg(["Hip rotation at foot plant",
                                 "Hip rotation at contact"])),
        ("SEPARATION", _sim_avg(["Peak hip-shoulder separation",
                                 "Separation at foot plant"])),
        ("TIMING",     _sim_avg(["Total swing duration",
                                 "Foot plant → launch",
                                 "Launch → contact"])),
        ("LOWER BODY", _sim_avg(["Re-extension", "Most bent (load)"])),
        ("STABILITY",  _sim_avg(["Total head drift",
                                 "Head drift Δx",
                                 "Head drift Δy"])),
    ]

    radar_h = 240
    need_space(radar_h + 10)

    # Two-column row: radar (left) + summary stats (right)
    radar_w = (W - MARGIN * 2) * 0.5 - 6
    summary_w = (W - MARGIN * 2) * 0.5 - 6
    card(MARGIN, y, radar_w, radar_h, fill=SURFACE_0, stroke=LINE)

    radar_cx = MARGIN + radar_w / 2
    radar_cy = y - radar_h / 2 + 10
    radar_chart(radar_axes, radar_cx, radar_cy, 90)

    # Legend below
    leg_y = y - radar_h + 16
    c.setStrokeColor(GREEN)
    c.setLineWidth(0.8)
    c.setDash(3, 3)
    c.line(MARGIN + 16, leg_y, MARGIN + 32, leg_y)
    c.setDash()
    c.setFillColor(INK_60)
    c.setFont("Helvetica", 7.5)
    c.drawString(MARGIN + 36, leg_y - 2, "MLB reference")
    c.setStrokeColor(RED)
    c.setLineWidth(1.2)
    c.line(MARGIN + 120, leg_y, MARGIN + 136, leg_y)
    c.drawString(MARGIN + 140, leg_y - 2, "Your swing")
    c.setLineWidth(1)

    # Right summary: axis percentages stacked
    sum_x = MARGIN + radar_w + 12
    card(sum_x, y, summary_w, radar_h, fill=SURFACE_0, stroke=LINE)
    red_dot(sum_x + 16, y - 18, 2.5)
    eyebrow(sum_x + 24, y - 21, "AXIS BREAKDOWN")

    row_y = y - 50
    for label, pct in radar_axes:
        c.setFillColor(INK_80)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(sum_x + 16, row_y, label)

        # Bar track
        bar_x = sum_x + 130
        bar_w = summary_w - (bar_x - sum_x) - 56
        c.setFillColor(SURFACE_2)
        c.roundRect(bar_x, row_y - 1, bar_w, 6, 3, fill=1, stroke=0)
        # Fill
        bar_color = band_color_for_pct(pct)
        fill_w = max(0.0, min(1.0, pct / 100.0)) * bar_w
        if fill_w > 1:
            c.setFillColor(bar_color)
            c.roundRect(bar_x, row_y - 1, fill_w, 6, 3, fill=1, stroke=0)
        # Pct on right
        c.setFillColor(INK_100)
        c.setFont("Helvetica-Bold", 9)
        c.drawRightString(sum_x + summary_w - 16, row_y,
                          f"{int(round(pct))}%")
        row_y -= 22

    # Overall similarity
    overall_sim = sum(p for _l, p in radar_axes) / max(len(radar_axes), 1)
    c.setStrokeColor(LINE)
    c.setLineWidth(0.5)
    c.line(sum_x + 16, row_y, sum_x + summary_w - 16, row_y)
    c.setLineWidth(1)
    c.setFillColor(INK_60)
    c.setFont("Helvetica-Bold", 7.5)
    c.drawString(sum_x + 16, row_y - 14, "OVERALL MLB SIMILARITY")
    c.setFillColor(RED)
    c.setFont("Helvetica-Bold", 16)
    c.drawRightString(sum_x + summary_w - 16, row_y - 18,
                      f"{int(round(overall_sim))}%")

    y -= radar_h + 22

    # ====================================================================
    #                       DETAILED METRIC BREAKDOWN
    # ====================================================================
    metric_table = record.get("metric_table") or {}
    if metric_table:
        need_space(70)
        section_eyebrow("07", "Detailed Breakdown")

        for group, rows in metric_table.items():
            if not rows:
                continue
            grp_h = 32 + len(rows) * 17 + 8
            need_space(grp_h + 8)

            card(MARGIN, y, W - MARGIN * 2, grp_h,
                 fill=SURFACE_0, stroke=LINE)

            c.setFillColor(INK_100)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(MARGIN + 16, y - 18, str(group))
            c.setStrokeColor(LINE)
            c.setLineWidth(0.5)
            c.line(MARGIN + 16, y - 24, W - MARGIN - 16, y - 24)
            c.setLineWidth(1)

            cur_y = y - 40
            label_w = 160
            bar_x = MARGIN + 16 + label_w + 12
            bar_w = (W - MARGIN - 16) - bar_x - 78
            pct_x = W - MARGIN - 16

            for r in rows:
                lbl = str(r.get("label", "—"))
                if r.get("flagged"):
                    lbl = "! " + lbl
                lbl = fit_text(lbl, "Helvetica", 8.5, label_w)

                pct = r.get("sim_pct")
                try:
                    pct_val = float(pct) if pct is not None else 0
                except Exception:
                    pct_val = 0

                c.setFillColor(INK_80)
                c.setFont("Helvetica", 8.5)
                c.drawString(MARGIN + 16, cur_y, lbl)

                c.setFillColor(SURFACE_2)
                c.roundRect(bar_x, cur_y - 1, bar_w, 5, 2.5, fill=1, stroke=0)
                if pct is not None and pct_val > 0:
                    c.setFillColor(band_color_for_pct(pct_val))
                    fw = max(2, min(1.0, pct_val / 100.0) * bar_w)
                    c.roundRect(bar_x, cur_y - 1, fw, 5, 2.5, fill=1, stroke=0)

                # You / Ref values above bar
                you_str = str(r.get("player_str", "—"))
                ref_str = str(r.get("ref_str", "—"))
                c.setFillColor(INK_60)
                c.setFont("Helvetica", 6.5)
                c.drawString(bar_x, cur_y + 6,
                             fit_text(f"You {you_str}  ·  Ref {ref_str}",
                                      "Helvetica", 6.5, bar_w))

                # Pct
                c.setFillColor(INK_100)
                c.setFont("Helvetica-Bold", 9)
                c.drawRightString(pct_x, cur_y,
                                  f"{int(round(pct_val))}%" if pct is not None else "—")

                cur_y -= 17

            y -= grp_h + 12

    # ====================================================================
    #                       PROGRESS — SCORE HISTORY LINE
    # ====================================================================
    if prog and prog.get("has_prior"):
        score_history = prog.get("score_history") or []
        if len(score_history) >= 2:
            need_space(170)
            section_eyebrow("08", "Progress")

            chart_h = 130
            card(MARGIN, y, W - MARGIN * 2, chart_h + 24,
                 fill=SURFACE_0, stroke=LINE)
            red_dot(MARGIN + 16, y - 18, 2.5)
            eyebrow(MARGIN + 24, y - 21, "SCORE HISTORY")

            # Draw the line chart
            pad_l = 36
            pad_r = 18
            pad_t = 36
            pad_b = 22
            chart_x0 = MARGIN + pad_l
            chart_y0 = y - chart_h - 4
            chart_w = W - MARGIN * 2 - pad_l - pad_r
            chart_yh = chart_h - pad_t - pad_b + pad_t  # actual plot height

            scores = [float(s) for _, s in score_history[-8:]]
            n = len(scores)

            def _px(i): return chart_x0 + (i / (n - 1)) * chart_w
            def _py(s): return chart_y0 + (s / 100.0) * (chart_h - pad_t - pad_b) + pad_b - 4

            # Reference grid: 0/50/100
            c.setStrokeColor(LINE)
            c.setLineWidth(0.4)
            for lvl in (0.0, 0.5, 1.0):
                gy = chart_y0 + lvl * (chart_h - pad_t - pad_b) + pad_b - 4
                c.line(chart_x0, gy, chart_x0 + chart_w, gy)
                c.setFillColor(INK_60)
                c.setFont("Helvetica", 6.5)
                c.drawRightString(chart_x0 - 6, gy - 2, str(int(lvl * 100)))
            c.setLineWidth(1)

            # Area
            area = c.beginPath()
            area.moveTo(_px(0), chart_y0 + pad_b - 4)
            for i, s in enumerate(scores):
                area.lineTo(_px(i), _py(s))
            area.lineTo(_px(n - 1), chart_y0 + pad_b - 4)
            area.close()
            c.setFillColor(SURFACE_2)
            c.drawPath(area, fill=1, stroke=0)

            # Line
            c.setStrokeColor(RED)
            c.setLineWidth(2)
            c.setLineCap(1)
            c.setLineJoin(1)
            line_p = c.beginPath()
            line_p.moveTo(_px(0), _py(scores[0]))
            for i in range(1, n):
                line_p.lineTo(_px(i), _py(scores[i]))
            c.drawPath(line_p, fill=0, stroke=1)
            c.setLineWidth(1)
            c.setLineCap(0)
            c.setLineJoin(0)

            # Dots + last-value label
            for i, s in enumerate(scores):
                c.setFillColor(RED if i == n - 1 else INK_60)
                c.circle(_px(i), _py(s), 2 if i < n - 1 else 3,
                         fill=1, stroke=0)
            c.setFillColor(RED)
            c.setFont("Helvetica-Bold", 9)
            c.drawString(_px(n - 1) + 6, _py(scores[-1]) - 2,
                         str(int(round(scores[-1]))))

            y -= chart_h + 36

    # ====================================================================
    #                       NEXT STEP CTA
    # ====================================================================
    p1_title = None
    p1_drill_name = None
    p1_drill_reps = None
    p1_why = None
    if cats:
        first = cats[0] or {}
        p1_title = first.get("title")
        p1_why = first.get("why_it_matters")
        d_list = first.get("drills") or []
        if d_list:
            d0 = d_list[0] or {}
            p1_drill_name = d0.get("name")
            p1_drill_reps = d0.get("reps")
    if not p1_title and fixes:
        f0 = fixes[0] or {}
        p1_title = f0.get("title") or "Priority 1"
        p1_why = f0.get("why")
        p1_drill_name = f0.get("fix_feel") or "Start with your Priority 1 drill"

    if p1_title or p1_drill_name:
        need_space(130)
        section_eyebrow("09", "Your Next Step")

        cta_h = 110
        card(MARGIN, y, W - MARGIN * 2, cta_h,
             fill=RED_DIM, stroke=RED, radius=10)

        c.setFillColor(RED)
        c.setFont("Helvetica-Bold", 7.5)
        c.drawString(MARGIN + 16, y - 18, "PRIORITY 1")

        c.setFillColor(INK_100)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(MARGIN + 16, y - 38,
                     fit_text(str(p1_title or "Priority 1"),
                              "Helvetica-Bold", 14, W - MARGIN * 2 - 32))

        drill_line = str(p1_drill_name or "Start with your Priority 1 drill")
        if p1_drill_reps:
            drill_line = f"{drill_line}   ·   {p1_drill_reps}"
        c.setFillColor(INK_80)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(MARGIN + 16, y - 56,
                     fit_text(drill_line, "Helvetica-Bold", 10,
                              W - MARGIN * 2 - 32))

        if p1_why:
            draw_wrapped(strip_html(str(p1_why)), MARGIN + 16, y - 72,
                         W - MARGIN * 2 - 32,
                         font="Helvetica", size=9, leading=12,
                         color=INK_60, max_lines=2)

        c.setFillColor(INK_60)
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(MARGIN + 16, y - 100,
                     "Train it. Re-upload. Compare — your next report will diff against this one.")

        y -= cta_h + 16

    # ====================================================================
    #                       COACH'S FULL NOTES (narrative)
    # ====================================================================
    narratives = record.get("narratives") or []
    coach_top = strip_html(coach_summary(record))
    extra_paras: List[str] = []
    if narratives:
        n0 = narratives[0]
        title_str = (n0.get("title") or "the top mechanic").title()
        why_str = n0.get("why") or ""
        extra_paras.append(
            f"The biggest unlock right now is {title_str}. {why_str}".strip()
        )
        if n0.get("fix_feel"):
            extra_paras.append(f"What the fix should feel like: {n0['fix_feel']}")
    if ref.get("style") and ref.get("name"):
        extra_paras.append(
            f"Watch {ref['name']} for the model — "
            f"{ref['style'].lower().rstrip('.')}."
        )

    if coach_top or extra_paras:
        need_space(80)
        section_eyebrow("10", "Coach's Full Notes")

        # Measure
        body_w = W - MARGIN * 2 - 32
        top_lines = wrapped_lines(coach_top, "Helvetica", 10, body_w) if coach_top else []
        extra_lines = []
        for para in extra_paras:
            extra_lines.extend(wrapped_lines(para, "Helvetica", 9.5, body_w))
            extra_lines.append("")  # blank between paragraphs
        if extra_lines and extra_lines[-1] == "":
            extra_lines.pop()
        notes_h = 26 + len(top_lines) * 14 + 14 + len(extra_lines) * 13 + 14
        need_space(notes_h + 6)

        card(MARGIN, y, W - MARGIN * 2, notes_h, fill=SURFACE_0, stroke=LINE)

        cur_y = y - 22
        # Left red stripe in the quote
        c.setFillColor(RED)
        c.rect(MARGIN + 16, cur_y - len(top_lines) * 14 - 2, 2,
               len(top_lines) * 14 + 4, fill=1, stroke=0)
        c.setFillColor(INK_100)
        c.setFont("Helvetica", 10)
        for line in top_lines:
            c.drawString(MARGIN + 26, cur_y, line)
            cur_y -= 14

        cur_y -= 6
        c.setFillColor(INK_80)
        c.setFont("Helvetica", 9.5)
        for line in extra_lines:
            if line == "":
                cur_y -= 6
                continue
            c.drawString(MARGIN + 16, cur_y, line)
            cur_y -= 13

        y -= notes_h + 14

    # ====================================================================
    #                       FINALIZE
    # ====================================================================
    footer(state["page"])
    c.save()
    buf.seek(0)
    return buf.getvalue()
